---
language: go

env:
  global:
    - GOARCH=amd64
    - GO15VENDOREXPERIMENT=1

go:
  - 1.6
  - 1.7
  - 1.8
  - tip

before_install:
  - go get -v github.com/Masterminds/glide
  - glide install

script:
  - cd ${TRAVIS_BUILD_DIR} && go test
